var SUPABASE_URL = 'https://gvbarymfbrcgywdjjrrj.supabase.co';
var SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2YmFyeW1mYnJjZ3l3ZGpqcnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyMjI5OTgsImV4cCI6MjA5ODc5ODk5OH0.VkEbk4kpBkVcI5cDSl3GZh__nRlMfoXHpwbgUK6AdOw';
